# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.product.com:
  peer0.manufacturer.product.com:
  peer1.manufacturer.product.com:
  peer0.agency.product.com:
  peer1.agency.product.com:
  peer0.retailer.product.com:
  peer1.retailer.product.com:
  peer0.distributor.product.com:
  peer1.distributor.product.com:

networks:
  byfn:

services:

  ca.product.com:
    extends:
      file: base/docker-compose-base.yaml
      service: ca.product.com
    container_name: ca.product.com
    networks:
      - byfn

  orderer.product.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.product.com
    container_name: orderer.product.com
    networks:
      - byfn

  peer0.manufacturer.product.com:
    container_name: peer0.manufacturer.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturer.product.com
    networks:
      - byfn

  peer1.manufacturer.product.com:
    container_name: peer1.manufacturer.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manufacturer.product.com
    networks:
      - byfn

  peer0.agency.product.com:
    container_name: peer0.agency.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.agency.product.com
    networks:
      - byfn

  peer1.agency.product.com:
    container_name: peer1.agency.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.agency.product.com
    networks:
      - byfn
  peer0.retailer.product.com:
    container_name: peer0.retailer.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.product.com
    networks:
      - byfn

  peer1.retailer.product.com:
    container_name: peer1.retailer.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.retailer.product.com
    networks:
      - byfn

  peer0.distributor.product.com:
    container_name: peer0.distributor.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.distributor.product.com
    networks:
      - byfn

  peer1.distributor.product.com:
    container_name: peer1.distributor.product.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.distributor.product.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.manufacturer.product.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.product.com/peers/peer0.manufacturer.product.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.product.com/peers/peer0.manufacturer.product.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.product.com/peers/peer0.manufacturer.product.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/manufacturer.product.com/users/Admin@manufacturer.product.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./../scripts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.product.com
      - peer0.manufacturer.product.com
      - peer1.manufacturer.product.com
      - peer0.agency.product.com
      - peer1.agency.product.com
      - peer0.retailer.product.com
      - peer1.retailer.product.com
      - peer0.distributor.product.com
      - peer1.distributor.product.com
    networks:
      - byfn
